version: "2"

networks:
  example:
    driver: bridge

services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:latest
    networks:
      - example
#    ports:
#      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: docker.io/bitnami/kafka:latest
    networks:
      - example
#    ports:
#      - "9092:9092"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
  vertica:
    image: docker.io/vertica/vertica-k8s:$VERTICA_K8S_VERSION
# Emulate x86 on Apple's M1 chip (demo purposes only)
#    platform: linux/amd64
    networks:
      - example
    #ports:
#      - "5433:5433"
#      - "5444:5444"
#    environment:
# This is important for Apple's M1 chip
#      - VERTICA_MEMDEBUG=2
